### ISSUE TITLE
"Error fetching update info: Invalid request!" Kernel update error c6903 honami. 

### ISSUE THREAD

**Issue by DVovan238** [OTAUpdateCenter/ota-updater-2.0#10]
I recently added the rom update to your site, and all seems to work fine. 
But than added some kernels and when I search for kernel updates I get "Error fetching update info: Invalid request!" error and toast notification "Invalid request!".
And I added all required files like in instructions. 
My device Xperia Z 1 c6903 honami.

**Comment by DVovan238** [comment]
Can someone fix it ?
😳

**Comment by DVovan238** [comment]
Is anyone here? 
😔

**Comment by DVovan238** [comment]
😞

**Comment by DVovan238** [comment]
😰

**Comment by DVovan238** [comment]
👹

**Comment by DVovan238** [comment]
🙈🙉🙊

**Comment by vetruvet** [comment]
Fixed in 2.0.4. Thank you for reporting the issue. 

Next time, please refrain from posting random emoticons daily. They do not contribute anything except junk notification emails in my inbox. This is an small (developer-wise) open-source project and you cannot really expect someone to be responding to issues right away.

**Comment by DVovan238** [comment]
Thank you :)
And I am sorry 😊
Was waiting too much.

Вы русский?
Спасибо.
Просто я лично смотрю чаще посты к своим роботам.
Извиняюсь.
Спасибо за поддержку 😃
11 окт. 2014 г. 2:29 пользователь "Valera Trubachev" <
notifications@github.com> написал:

**Comment by DVovan238** [comment]
Thank you very much 😊

**Comment by DVovan238** [comment]
Sorry 😊

**Comment by DVovan238** [comment]
And thank you for your work. 
Great app!  😃

**Comment by DVovan238** [comment]
Sorry for asking, but now the kernel ID is same one of ram.ota.prop?!
Because I set the kernel.ota.prop diferent ID…
12 окт. 2014 г. 20:17 пользователь "Володимир Дрань" <
volodymyrdran@gmail.com> написал:

**Comment by DVovan238** [comment]
I was thinking that those can be diferent.
12 окт. 2014 г. 20:17 пользователь "Володимир Дрань" <
volodymyrdran@gmail.com> написал:

**Comment by DVovan238** [comment]
The same from rom.ota.prop

**Comment by DVovan238** [comment]
?

**Comment by DVovan238** [comment]
How I will put 2 updates for the same device?
How I understand it is impossible  with the same update ID?!!!
12 окт. 2014 г. 20:35 пользователь "Володимир Дрань" <
volodymyrdran@gmail.com> написал:

**Comment by DVovan238** [comment]
How I understand this, must be 2 ID'S .
One in rom.ota.prop and second in kernel.ota.prop. 
If not 2 sections in update center have no sense! 
If it possible update rom with kernel, no?!!!
So how I understand it must be 2 "channel's" for updates. 
One ROM with ID from rom.ota.prop, and second KERNEL with ID from kernel.ota.prop ?
If I'm wrong, or just understand something wrong please let me know! 
Or if both ID'S must be the same…

**Comment by DVovan238** [comment]
But the idea is great.

**Comment by DVovan238** [comment]
Sorry but I will  put the new error report. 
Because I think is a BUG, that the kernel update work(go) with the same update id as the kernel. 
Please respond me !
😳

**Comment by DVovan238** [comment]
I use criskello rom. 
But I developed Cyanogenmod 11 based rom. 
You can find all updates on your site. 
And some Kernels for CM11.
Only for Xperia Z 1 c6903 HONAMI. 
This is my device.

**Comment by DVovan238** [comment]
And I wanted to update kernels apart with a ROM .
But now I see it's not the point of yoyour app.

**Comment by DVovan238** [comment]
Sorry for my bad English, I'm Ukrainian ☺

**Comment by DVovan238** [comment]
And now a little bit drunk 😖

**Comment by DVovan238** [comment]
So how I understand the update ID'S must be the same in rom.ota.prop and kernel.ota.prop?!!!

**Comment by DVovan238** [comment]
And I can't develop the kernel for other rom?! 
And update rom with other kernel?! 
Updatable with your app. 
Then your app lose 50% off benefits, that I thinks hi have.

**Comment by DVovan238** [comment]
Because flash xxxx.ota.prop with Clock Work Mod recovery it's not a problem even for noobs.

**Comment by vetruvet** [comment]
Your hardly-coherent rapid-fire comments DO NOT HELP! If you are drunk as you say, DON'T WRITE ANYTHING. Write something coherent and in one comment, without spamming my inbox with useless notifications!!!!!

Please try with v2.0.5, I think the issue you are having is fixed there.
