### ISSUE TITLE
Invalid Kernel ID

### ISSUE THREAD

**Issue by Matx13** [OTAUpdateCenter/ota-updater-2.0#11]
Hello,

OTA Updater 2.0.4 
Android 4.2.2 MTK 6589.

-->  ID is identical !
![screenshot_2014-10-11-19-52-54](https://cloud.githubusercontent.com/assets/9142529/4603536/a16e73e4-516f-11e4-9b3e-a729918aadc0.png)
![screenshot_2014-10-11-20-01-12](https://cloud.githubusercontent.com/assets/9142529/4603564/ac88abd6-5170-11e4-88a7-ba0f9dd0585e.png)
![otak](https://cloud.githubusercontent.com/assets/9142529/4603549/3e070554-5170-11e4-9cc5-03fbaeefe7a5.png)

I wipe cache, wipe data app, reinstall the app, created a new ID for testing, always the same, what to do? thank you!

**Comment by vetruvet** [comment]
Fixed in 2.0.5. Please try again with the new version.
