### ISSUE TITLE
noflash not working (still flashing via app allowed)

### ISSUE THREAD

**Issue by MardonHH** [OTAUpdateCenter/ota-updater-2.0#12]
Content of ota.prop
{
    "noflash": "true"
}

**Comment by vetruvet** [comment]
Please try:

```
{
"noflash": true
}
```

I think the example on the site may be wrong (has quotes and it shouldn't).

**Comment by MardonHH** [comment]
hmm ota.prop also has quotes and it works..
"otaid": "cm11-anzu"

**Comment by vetruvet** [comment]
Yes, that is correct. The reason for no quotes around true/false is that they are boolean values and not strings.
