### ISSUE TITLE
Note 3 RC Elite Team s5 Port OTA Update Issue

### ISSUE THREAD

**Issue by willlk** [OTAUpdateCenter/ota-updater-2.0#13]
Hey guys, need some assistance.
I have a Canadian Note 3 w/ the RC Elite s5 Port v17.0 and Compulsion Kernal 3.4.95. I am having an issue using OTA Update... I have download the update and selected to wipe the cache, but when the updater goes into recovery, it runs for 2 seconds and then boots into the OS without the update

Any suggestions?

**Comment by M3NTI0N** [comment]
Yep.
Ask Your ROM Developers friendly to fix THIS problem.
Thanks.

Regards,
M3nti0n

**Comment by vetruvet** [comment]
Hold on, do that, but also please provide the recovery type and version that you are using.

**Comment by cstayton** [comment]
I am also experiencing this issue on Samsung Galaxy S5 (klteatt) with SafeStrap recovery which is based off of TWRP 2.7.1.0. if i remove the check mark from wipe cache everything works as expected. maybe add an ota.prop capability for noWipeCache i.e "NoWipeCache": true/false? would be a nice addition.
