### ISSUE TITLE
Missing OTA Feature File

### ISSUE THREAD

**Issue by Matx13** [OTAUpdateCenter/ota-updater-2.0#14]
Hello,

Android 4.4.2, Mediatek 6589, OTA Updater 2.0.5 (system/app)
Cat log : http://justpaste.it/hucd

The files are present:
![screenshot_2014-11-04-22-09-51](https://cloud.githubusercontent.com/assets/9142529/4908260/5f953ac8-6468-11e4-9466-38a2af2e79bd.png)
Have seen it hère, but once I click download : force close.
![screenshot_2014-11-04-22-09-59](https://cloud.githubusercontent.com/assets/9142529/4908261/5f9726da-6468-11e4-8f29-e857fe208391.png)
![screenshot_2014-11-04-22-10-05](https://cloud.githubusercontent.com/assets/9142529/4908262/5f9f2164-6468-11e4-8300-78489a51b9d3.png)
![screenshot_2014-11-04-22-10-08](https://cloud.githubusercontent.com/assets/9142529/4908263/5fa03e32-6468-11e4-9e0c-03e0252a5361.png)

Thank you!

**Comment by vetruvet** [comment]
Download URL did not have a http:// in front of it. Please include that as it may be https:// or ftp:// so we don't assume it's http:// . I've fixed it for you in your ROM this time.
