### ISSUE TITLE
Constant notification present, saying there is an update to (example) v 1.2.0, when the installed ROM is v 1.2.0

### ISSUE THREAD

**Issue by mesmerus** [OTAUpdateCenter/ota-updater-2.0#19]
I have 4 phones, and two roms (aurora & aurora-beta) -- one phone is in the beta branch, and the other three are in the main branch (so I can beta test, rolling back and foward with CWM-R as needed).

For the past few days (maybe week now?) I have noticed a constant notification for 'OTA Update' (Second line 'OTA ROM Update Available'). It appears as a standard push notification, however it is incorrect about there being an update -- I have not updated either rom since September 2014 (from lack of need/time). When I attempt to download this 'update', it never starts downloading (on WiFi or Mobile Data), and the application then locks up and causes some odd issues (such as random glitching between downloading the update or notifying of one). Rebooting the phone does not solve these issues, however recovering from a CWM-R backup (obviously) does solve the issues (by them never having happened).

Things I could do if/when I have more time, but have not yet:
- Try removing the update and re-adding the update for both roms.
- Attempt to clear data on the application, and see if the problem persists.

Literally nothing has changed in my setup with the application, and I have authored no updates (there are no authors but myself for both roms) since September 2014, so this issue is out of the blue and completely random; there is nothing to my knowledge that I have done that could have caused this, since all 4 phones/2 roms are affected (and only 1 phone, on the beta rom is my personal phone -- the other three are in family member's hands all day).

I can provide my rom.ota.prop if it may be of help for comparison/confirmation (although the site will say the same things). I cannot provide a kernel.ota.prop, as I do not use OTAUpdateCenter to update the kernel (or rather, I cannot update the kernel unless the fourth wall is broken and Qualcomm releases unobfusicated binaries for the msm8625 :( ).

I am (very) capable of helping solve this issue, not from a backend standpoint (I don't know the code the group is using), but I can easily do CWM-R backups, test something, and recover if needed. All 4 phones can do this, but only the one phone in the aurora-beta rom would be used for this (my phone; kinda the entire purpose of having a *-beta rom).

Also of note, I can see the changelog (correct) for the 'update', and the application reports the update is for version 1.2.0, when the ROM Version field also has the same version. Attached are some screenshots of relevant content/discussion; if more content is needed from me to assist in solving this, I will hapily help as I can, and should respond within 48 hours. Sorry about the screenshots being more on the hallogen side; I use Twilight (have for months since prior to ever using OTA Update Center, so not a possible cause) to prevent my eyes from being hurt as evening grows closer (also use Redshift on the laptop for same reasoning); it was active when I took these, and I didn't think about it beforehand, so they might be a bit more red than usual.

http://imgur.com/a/Pc97c

The phones in question are all identical: 'BLU Studio 5.0S (D570A)' models.
GSM Arena page for the phone (lists both D570A American and D570I International; we have the D570A): http://www.gsmarena.com/blu_studio_5_0_s-5459.php

Up until this point in time, (literally) everything has worked perfectly as intended for updating the ROM, automatically rebooting into recovery, flashing the update, downloading the update(s), etc.

**Comment by M3NTI0N** [comment]
Hello,

Sorry for the late reply, but I was moving home ;)
I would like to help you, but for that I need more information.

Would you like to send me a mail on info@otaupdatecenter.pro with the problem explained?
This mail needs to include the otaid, OTA version, and the ROM.OTA.prop

Thanks in advance.

Regards,
M3nti0n
