### ISSUE TITLE
location of the directory ota

### ISSUE THREAD

**Issue by ptsantosrj-zz** [OTAUpdateCenter/ota-updater-2.0#20]
The OTA search the rom data / media / 0 / 0 , but the system loads the ota folder data / media / 0 . Is there any solution without copying the contents to the / 0 / 0 ? All rom the users will have to proceed in this way ?

**Comment by M3NTI0N** [comment]
This is mentioned on the F.A.Q. on HTTPS://otaupdatecenter.pro:

Your device may have non-standard storage paths. Find out if the OS and/or recovery have non-standard storage paths and set them in the /system/ota.prop file.

Optional settings for /system/ota.prop file:
{
    "noflash": "<< true or false - prevents app from rebooting into recovery for flashing (user must flash manually) >>",
    "rebootcmd": "<< reboot command if different than `reboot recovery` (can be a script included with ROM/Kernel) >>",
    "system_sdpath": "<< path to external storage in OS if it's non-standard >>",
    "recovery_sdpath": "<< path to external storage in recovery if it's non-standard >>"
}

For example:
{
    "system_sdpath": "/media/0"
}
