### ISSUE TITLE
ROM download on ethernet port not working

### ISSUE THREAD

**Issue by fsltd** [OTAUpdateCenter/ota-updater-2.0#28]
Hi. I've issue with OTA Updater and ethernet port. OTA Updater only downloads new firmware on wifi connection. If I turn on ethernet port and turn off wifi on my android tv device, it do not download (just saying waiting for data 0 bytes). I also unchecked Wifi only downloads in settings but it doesn't help

**Comment by alasmi** [comment]
tkanks

**Comment by jamalabdillah** [comment]
On
