### ISSUE TITLE
Ota-updater-v2.0.5-force-closes-whenever-I-try-downloading-a-new-update

### ISSUE THREAD

**Issue by charickj** [OTAUpdateCenter/ota-updater-2.0#31]
#31 Ota-updater-v2.0.5-force-closes-whenever-I-try-downloading-a-new-update

please help me, I always trying to download my new update that I been uploaded to your site, the notification will pop up on my phone but when I click download update it's force stop the apps my phone is cherry mobile flare S (q360) and I uploaded my created rom to your site.

**Comment by freaking1** [comment]
Ur

**Comment by rozaimialli** [comment]
GOOD
