### ISSUE TITLE
Unable to get download status

### ISSUE THREAD

**Issue by jimbaco** [OTAUpdateCenter/ota-updater-2.0#35]
Hi,

Receiving this error while attempting to update.what do I do?

**Comment by lil-rob** [comment]
I have no idea either

**Comment by newandroid** [comment]
me too, is my service question?
there are some logs:
Aborting request for download 8: Failed reading response: java.net.SocketTimeoutException
Download 8 finished with status WAITING_TO_RETRY
Aborting request for download 8: Unhandled HTTP response: 412 Precondition Failed
Download 8 finished with status PRECONDITION_FAILED
