### ISSUE TITLE
Crash On Android 5.1

### ISSUE THREAD

**Issue by muzilike** [OTAUpdateCenter/ota-updater-2.0#36]
W/System.err( 4144): java.io.IOException: Error running exec(). Command: [su] Working Directory: null Environment: null
  W/System.err( 4144):    at java.lang.ProcessManager.exec(ProcessManager.java:211)
  W/System.err( 4144):    at java.lang.Runtime.exec(Runtime.java:173)
  W/System.err( 4144):    at java.lang.Runtime.exec(Runtime.java:246)
  W/System.err( 4144):    at java.lang.Runtime.exec(Runtime.java:189)
  W/System.err( 4144):    at com.otaupdater.DownloadsActivity.flashFiles(DownloadsActivity.java:259)
  W/System.err( 4144):    at com.otaupdater.DownloadsActivity.access$000(DownloadsActivity.java:51)
  W/System.err( 4144):    at com.otaupdater.DownloadsActivity$2$1.onClick(DownloadsActivity.java:193)
  W/System.err( 4144):    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
  W/System.err( 4144):    at android.os.Handler.dispatchMessage(Handler.java:102)
  W/System.err( 4144):    at android.os.Looper.loop(Looper.java:135)
  W/System.err( 4144):    at android.app.ActivityThread.main(ActivityThread.java:5257)
  W/System.err( 4144):    at java.lang.reflect.Method.invoke(Native Method)
  W/System.err( 4144):    at java.lang.reflect.Method.invoke(Method.java:372)
  W/System.err( 4144):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
  W/System.err( 4144):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
  W/System.err( 4144): Caused by: java.io.IOException: Permission denied
  W/System.err( 4144):    at java.lang.ProcessManager.exec(Native Method)
  W/System.err( 4144):    at java.lang.ProcessManager.exec(ProcessManager.java:209)

**Comment by cuocdoilonnhudongsong** [comment]
Give android 5.0 me

**Comment by mclub198456** [comment]
Update ota
