### ISSUE TITLE
htc one m8 GPE: OTA Update for mra58k.h10 fails: E: Error in cache/update.zip (status 7)

### ISSUE THREAD

**Issue by jsethi3** [OTAUpdateCenter/ota-updater-2.0#39]
I tried to auto update the  mra58k.h10  and it fails every time with message: fails: E: Error in cache/update.zip (status 7)

**Comment by mohmed1500** [comment]
Zip

**Comment by artemcarabash** [comment]
same issue

**Comment by srinivasaraja** [comment]
how can i resolve this problem

**Comment by joeyluu** [comment]
Jseth were you able to solve this? I'm having the same issue with my brand new m8 gpe
