### ISSUE TITLE
Automatic update fails when cache is cleared

### ISSUE THREAD

**Issue by Locutu5** [OTAUpdateCenter/ota-updater-2.0#40]
When a new updated is downloaded and the user wants to flash it the clear cache setting is automatically selected. The device reboots into TWRP and clears the cache but doesn't install the update. It then reboots the device.

When the clear cache setting is not selected the device reboots into TWRP and flashes the update properly.

Using OTA Updater V2.0.5

**Comment by arny24x7** [comment]
Dont worry...The developer has gone into deepsleep. I donated money to get better support but surprised to see the devs absolute retarded response.

**Comment by Locutu5** [comment]
Does this mean that the issue has been resolved?
