### ISSUE TITLE
Loading in recovery, upgrade firmware does not start.

### ISSUE THREAD

**Issue by Blacknuber-ru** [OTAUpdateCenter/ota-updater-2.0#41]
I write through the Google translator from Russian.
Update OTA downloaded. I press the button to install - comes to recovery, but the update is not installed. On the screen there are no errors.
ROM - https://www.otaupdatecenter.pro/roms/S820_MiuiPro
[log_00001-20160506-225450.txt](https://github.com/OTAUpdateCenter/ota-updater-2.0/files/252375/log_00001-20160506-225450.txt)
[Log_recovery.txt](https://github.com/OTAUpdateCenter/ota-updater-2.0/files/252385/Log_recovery.txt)
file to install the update https://yadi.sk/d/MjiupBrarXqb7
Maybe miui some libraries do not have enough?

**Comment by kengraWin** [comment]
good
