### ISSUE TITLE
unsupported rom and kernel

### ISSUE THREAD

**Issue by surain69** [OTAUpdateCenter/ota-updater-2.0#46]
Hello,
My mobile is Samsung galaxy grand neo i9060, I purchased the handset last year since then I am not yet received any updates.Now when I tried to update it from your site, it says Unsupported ROM/Kernel, the feature XML file is missing from my ROM/Kernel.Without this file I will not be able to update my device.Kindly do the needful to update my device.
Thank you

**Comment by thedirtdevil** [comment]
my mobile is samsung s3 mini..this phone was gived by dato' adnan himself as a present for me..my problem now is same as surain69..kindly need to update my device cos im trying to this since2015..thank you..
