### ISSUE TITLE
ota update......

### ISSUE THREAD

**Issue by veenitk** [OTAUpdateCenter/ota-updater-2.0#5]
I am getting a message that I have wrong kernel...canvas 2+

**Comment by vetruvet** [comment]
Specific error message or logcat if the app is crashing please.

**Comment by veenitk** [comment]
Kernel.ota.prop missing

**Comment by veenitk** [comment]
2.3.0 version  ots

**Comment by vetruvet** [comment]
Please provide contents of /system/kernel.ota.prop

Also, version 2.3.0 is not out, I assume you mean 2.0.3

**Comment by Matx13** [comment]
Hello, "Kernel.ota.prop missing"
where is the box -> ""fullver": "<< Output of `cat /proc/version` >>"" on the website https://otaupdatecenter.pro ?!

![ota](https://cloud.githubusercontent.com/assets/9142529/4599331/cb33ef98-50c4-11e4-9679-c01d793e8fd0.png)

Thankyou.

**Comment by vetruvet** [comment]
@Matx13:
1. Install kernel on device
2. On computer run: `adb shell cat /proc/version`
3. Copy/paste into kernel.ota.prop file
4. **Next time, please comment on the correct issue or open a new one instead of hijacking whatever issue you feel like.**

**Comment by Matx13** [comment]
Ok. thank you

**Comment by anishgurjar7** [comment]
Where can I find kernel file
My issue is
Kernel.ota.prop missing 
Alice project
Kernel 3.4.67

**Comment by mani12345678** [comment]
Device
Spark
Kernel
3.10.54
queen@scmbuild#1
Tuesday jun 16 21:34:01 CST 2015

**Comment by kohandel** [comment]
It's very good.
