### ISSUE TITLE
OTA Updater v2.0.5 crashes 

### ISSUE THREAD

**Issue by GamerROMInc** [OTAUpdateCenter/ota-updater-2.0#54]
The OTA Updater app v2.0.5 crashes wjen i click download to test if itll download, the app reconizes the update but crashes when i click download any help to fix this?

**Comment by edrcfyhb** [comment]
asxdfghj

**Comment by fahadkgh1346** [comment]
Legal Persian

**Comment by artem8844** [comment]
Ff

**Comment by arif1413** [comment]
I want

**Comment by arif1413** [comment]
yes
