### ISSUE TITLE
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by Drjacky** [OTAUpdateCenter/ota-updater-2.0#57]
When I click on "Available Updates" button manually, It says:
![image](https://user-images.githubusercontent.com/2296754/27782834-5b5c2ea6-5fe9-11e7-9e35-07d6be9f451e.png)

And in the logcat:
![image](https://user-images.githubusercontent.com/2296754/27782848-641da8e4-5fe9-11e7-8c1b-df1c2a57d0d0.png)

I set my own ROM as private.
_______________
Now when I set it as public, I get this logcat:
![image](https://user-images.githubusercontent.com/2296754/27783124-30087c5e-5fea-11e7-99c1-346a9a3bf653.png)

**Comment by kengraWin** [comment]
good
