### ISSUE TITLE
Unsupported Rom 

### ISSUE THREAD

**Issue by narendrag432** [OTAUpdateCenter/ota-updater-2.0#58]
Hi ,Im using S905x TV media box,create account in OTA Update centre and placed my OTA zip file.
In S905x TV media box instilled OTA-Updater-2.0.5.apk .
In this application getting like "**Unsupported Rom**"
The Rom developer has not enabled for the OTA updater! Please ask them(kindly) to add support before using this app(rom.ota.prop missing).
Could you please guide to resolve this problem.

**Comment by gizby** [comment]
otg

**Comment by DeHutch** [comment]
I have same issue, could you please help me?
