### ISSUE TITLE
Doesn't reboot into recovery

### ISSUE THREAD

**Issue by ruben2s** [OTAUpdateCenter/ota-updater-2.0#6]
Hi, when I tap flash update, the device doesn't reboot into recovery, it doesn't do anything. Only it asks for root permission.
Device: Samsung Galaxy S4 mini with rom id: serranos_s5_proyect

**Comment by vetruvet** [comment]
Please provide logcat and ROM/kernel OTA ID

**Comment by ruben2s** [comment]
I updated the issue

**Comment by vetruvet** [comment]
Please run "adb shell reboot recovery" from a terminal (on your computer with the phone plugged in) and let me know the output of that and if the phone reboots into recovery successfully.

**Comment by ruben2s** [comment]
C:\Program Files (x86)\Android\android-sdk\platform-tools>adb shell reboot recovery
Done
C:\Program Files (x86)\Android\android-sdk\platform-tools>

It reboots and enters to the recovery

**Comment by vetruvet** [comment]
Sorry for the delay, been very busy lately. 

What version of the app are you using? Also, please post the content of rom.ota.prop, ota.prop (if present), or if not using those files (v1 configuration), then any otaupdater lines in build.prop.

**Comment by marcothien** [comment]
yyyyyyyyyyyyyyyy
