### ISSUE TITLE
Kernel.ota.prop not found issue

### ISSUE THREAD

**Issue by chevanlol360** [OTAUpdateCenter/ota-updater-2.0#8]
I have set my my OTA stuff perfectly and the app wont sense that i have the kernel.ota.prop installed. instead if just gives me unsupported kernel error

**Comment by dexter93** [comment]
Hi! Please provide kernel name, OTA ID and the location as well as the contents of the kernel.ota.prop

**Comment by anishgurjar7** [comment]
Alice phone
Kernel - 3.4.67
              Buildslave@mxws54

Issue - kernel.ota.prop missing

**Comment by April77** [comment]
My kerneln rom, same thing

**Comment by srinivasaraja** [comment]
Device - msm8610
ROM - UTLOPN9v1021
kernal - 3.4.0
Builder@taishan#1
Wed jun 11 19:59:15 CST 2014
Issue - ROM/Kernal missing please add the file.

**Comment by mani12345678** [comment]
Device
Spark
Kernel
3.10.54
queen@scmbuid#1
Tuesday jun 16 12:34:01 CST 2015

**Comment by DeHutch** [comment]
Device:
me301t

Kernel:
3.1.10-gab03a80
android@taurus#1
Fri aug 23 19:17:58 CST 2013

kernel.ota.propmissing
Could you please help me?
