### ISSUE TITLE
unable to download the update...

### ISSUE THREAD

**Issue by santanu01101987** [OTAUpdateCenter/ota-updater-2.0#9]
Dear seniors, i'm unable to download the OTA update...as it's showing "there was an error with the download"...attachd is the screenshot...

**Comment by santanu01101987** [comment]
Sorry...cant upload pic...available update is "Stock_V3_NeroD(version 1.2)"...whereas im on version 1...plz plz plz help...

**Comment by vetruvet** [comment]
This is an issue with the ROM author. They put in a bad download link into the ROM. 
The 1.2 update links to https://dl-web.dropbox.com/get/StockV3.2-signed.zip?_subject_uid=109678028&w=AACA0Zj0_NdELcNcVRvDounQVa8JtFZ6piyCsF6aNov0vQ&dl=1 which is a private file on dropbox. 
Please ask the ROM author to make the file public so people can update it.
